### PR TITLE
Added docker container for quick review of an application.

### PR DESCRIPTION
**Pull request by BBerastegui**

### CODE REVIEW

**Comment by vincentcox** [comment]
Can you confirm that the docker instance still works with https://github.com/vincentcox/StaCoAn/tree/develop? 
I am cleaning up the structure. Currently I am unable to run docker because I am running VMWare to test the different builds. Unfortunately, hyper-V does not like VMWare so I cannot test it on my device. 

Build is [passing](https://travis-ci.org/vincentcox/StaCoAn/builds/340083250), so if docker works for you, it will be merged to master.

**Comment by vincentcox** [comment]
I update the docker setup with a drag and drop interface. It's now pushed to  [develop](https://github.com/vincentcox/StaCoAn/tree/develop). 
Again, I have no access to docker due vmware, so it would be a huge favour if you could test this again.
Do you mind if I put you in a "special contributor's" tab in the `README`? If you like I link your GitHub or twitter account. Your docker idea and code gave this project something extra so I would like to express my appreciation.

**Comment by BBerastegui** [comment]
Hi ! I just took a look at it.

The docker now is much much smaller, but here: https://github.com/vincentcox/StaCoAn/blob/develop/src/helpers/server.py#L442

You have hardcoded a port (8080) for the report to be opened, but by default, the web server is running in port 8000, so when you click on it, you get an error, as the server is not running in that port.

Am I missing something here?

Feel free to add me wherever you want. Glad I helped a little !

**Comment by vincentcox** [comment]
Hi there, 

You were correct!

Somehow my latest commit didn’t get trough.

Now it should work, can you try again?

I will add your twitter handle in the next commit! 🙌

**Comment by BBerastegui** [comment]
Isn't supposed to run the web server if I start it like this instead of giving this error?

```
# python /StaCoAn/src/stacoan.py --enable-server
[INFO] Decompiling app...
[ERROR] No mobile app detected, exiting! Hgnnnhh
```

**Comment by BBerastegui** [comment]
When cloning the develop branch I still get the link to the port 8080, and the name of the report location is not ok neither (check the `.` and the underscores).

Link generated:
`http://localhost:8080/com_king.candycrushsaga.apk/report/start.html`

Link corrected:
`http://localhost:8000/com_king_candycrushsaga_apk/report/start.html`

**Comment by vincentcox** [comment]
Damn, will look at it this evening. Thanks for testing it!

**Comment by vincentcox** [comment]
Just to double check, did you changed https://github.com/vincentcox/StaCoAn/blob/develop/docker/Dockerfile#L19 to `RUN git clone https://github.com/vincentcox/StaCoAn/ -b develop`?

**Comment by BBerastegui** [comment]
Yup:

```
# git branch
* develop
```

 The HTML I end up with is like this:

`<a href="http://localhost:8080/com_king.candycrushsaga.apk/report/start.html" class="box__restart2" id="done_link" onclick="javascript:event.target.port=8080" role="button" target="_blank">Open report!</a>`

**Comment by vincentcox** [comment]
https://github.com/vincentcox/StaCoAn/commit/b2099e38401e1d53ebd45d975a1026a7b3e9340e
-> This fixes the path error you have. 
About your comment over the port; there are 2 ports used: 
* 8000 for drag and drop server
* 8080 for the report server

**Comment by vincentcox** [comment]
https://github.com/vincentcox/StaCoAn/tree/develop#top-contributors There you go! 😃

**Comment by Ayowel** [comment]
@vincentcox  Then, you might want to `EXPOSE 8080` in the Dockerfile and update the readme

**Pull request merged**
